# Generated by Django 4.0.4 on 2022-05-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0002_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
