version: "3"

services:
    redis:
        image: redis
    db:
        image: postgres:10
        stop_signal: SIGINT
        environment:
            - POSTGRES_DB=hostdb
            - POSTGRES_USER=host
            - POSTGRES_PASSWORD=host123
        # volumes: 
        #     - ./misc/dbdata:/var/lib/postgresql/data:delegated
        
    web:
        command: >
          bash -c "while !nc -w 1 -z db 5432;
                   do sleep 0.5;
                   done;
                   
                   ./manage.py migrate;
                   
                   while :;
                   do exec ./manage.py runserver 0.0.0.0:8000;
                   done;
                   "
        image: "web"
        build: .
        stop_signal: SIGINT
        stdin_open: true
        tty: true
        volumes: 
            - .:/code:cached
        ports: 
            - "8000:8000"
        depends_on:
            - db
            - redis
        environment: 
            IN_DOCKER: 1
    
    celery:
        build: .
        command: celery -A videoprocessing worker -l info
        volumes:
            - .:/usr/src/app/
        environment: 
            IN_DOCKER: 1
        depends_on:
            - redis
        